- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: installing-nodejs.yaml
- name: setting up app directory
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app.yaml    